### ISSUE TITLE
Geometries in geometry column in bigquery-public-data.geo_openstreetmap.planet_ways are all NULL

### ISSUE THREAD

**Issue by francois-baptiste** [gcp-pdp/geo-openstreetmap#33]
Geometries in geometry column in bigquery-public-data.geo_openstreetmap.planet_ways are all NULL.
![image](https://user-images.githubusercontent.com/7817985/129580634-c31f833d-8996-48cd-99dc-b89de66921a4.png)

**Comment by Jesus89** [comment]
It looks like you run the query in the middle of an update (Last modified Aug 16, 2021, 8:42:50 PM UTC+2), because of the bytes processed in your query (134.6 GB).

When I run the query now it processes 322.1 GB and it returns !NULL geometries. However, there are NULL geometries in the table, and it would be nice to know if this is OK or not.

![](https://user-images.githubusercontent.com/2227572/129629491-ed8299c2-7d01-445a-936a-835b0def0d72.png)

**Comment by francois-baptiste** [comment]
I close this one and fill in a feature request to get an atomic update mechanism.

**Comment by francois-baptiste** [comment]
> I close this one and fill in a feature request to get an atomic update mechanism.

#34
